name: myprojectt

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Build:

    runs-on: myrunner

    steps:
    - name: Checkout code from Github
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Install maven
      run: |
           sudo apt-get update -y
           sudo apt install maven default-jdk -y
           sudo apt install unzip -y
        
    - name: Build with Maven
      run: mvn clean package
   
  Test: 
    runs-on: myrunner

    steps:
    - name: Build and SonarQube Scan
      run: |
           mvn clean verify sonar:sonar \
           -Dsonar.host.url=${{ vars.SONAR_HOST_URL }} \
           -Dsonar.token=${{ secrets.SONAR_TOKEN }}


    - name: OWASP Dependency Check
      run: |
           cd /home/ubuntu/dependency-check
           ./bin/dependency-check.sh \
           --scan . \
           --out reports \
           --data /home/ubuntu/dependency-check/data \
           --noupdate
     
